---
# For openstack VMs modify the mount point below depending on if the Openstack
# VM deploy tool defaults to mounting ephemeral disks
- name: umount ceph disk (if on openstack)
  mount:
    name: /mnt
    src: /dev/vdb
    fstype: ext3
    state: unmounted
  when:
    - ceph_docker_on_openstack

- name: generate ceph osd docker run script
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-osd-run.sh.j2"
    dest: "{{ ceph_osd_docker_run_script_path }}/ceph-osd-run.sh"
    owner: "root"
    group: "root"
    mode: "0744"

- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-osd.service.j2"
    dest: /etc/systemd/system/ceph-osd@.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: find osd id based on the device
  command: >
    docker run --name expose_partitions_{{ item | to_uuid }}
    --privileged=true
    -v /dev/:/dev/
    -v /etc/ceph:/etc/ceph
    -e OSD_DEVICE=/dev/{{ item | to_uuid }}
    -e DISK_LIST_SEARCH=whoami
    {{ ceph_docker_registry }}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}
    disk_list
  changed_when: false
  with_items: "{{ devices }}"
  register: osd_ids

- name: remove find osd id container
  docker:
    name: "expose_partitions_{{ item | to_uuid }}"
    state: absent
  with_items: "{{ devices }}"

- name: systemd start osd container
  systemd:
    name: ceph-osd@{{ item.stdout }}
    state: started
    enabled: yes
    daemon_reload: yes
  changed_when: false
  with_items: "{{ osd_ids.results }}"
