---
- name: verify the osd_group_name is valid
  fail:
    msg: "osd_group_name is either not defined or not a member of group_names"
  when:
    - osd_group_name is not defined or osd_group_name not in group_names

- name: make sure public_network configured
  fail:
    msg: "public_network must be configured. Ceph public network"
  when:
    - public_network == '0.0.0.0/0'

- name: make sure cluster_network configured
  fail:
    msg: "cluster_network must be configured. Ceph replication network"
  when:
    - cluster_network == '0.0.0.0/0'
    - not containerized_deployment

- name: make sure journal_size configured
  debug:
    msg: "WARNING: journal_size is configured to {{ journal_size }}, which is less than 5GB. This is not recommended and can lead to severe issues."
  when:
    - journal_size|int < 5120
    - osd_objectstore == 'filestore'

- name: verify a valid osd scenario was chosen
  fail:
    msg: "The scenario {{ osd_scenario }} is invalid or not supported, valid scenarios are {{ valid_osd_scenarios }}"
  when:
    - osd_scenario not in valid_osd_scenarios

- name: verify devices have been populated in non-auto discovery
  fail:
    msg: "specify discovery option or pre-populate devices for your osd scenario"
  when:
    - collocated or non_collocated
    - not osd_auto_discovery
    - devices|length == 0

- name: check if osd_scenario lvm is supported by the selected ceph version
  fail:
    msg: "osd_scenario lvm is not supported by the selected Ceph version, use Luminous or newer."
  when:
    - not containerized_deployment
    - lvm
    - ceph_release_num[ceph_release] < ceph_release_num.luminous

- name: verify lvm_volumes have been provided
  fail:
    msg: "please provide lvm_volumes to your osd scenario"
  when:
    - lvm
    - not osd_auto_discovery
    - lvm_volumes|length == 0

- name: make sure the lvm_volumes variable is a list
  fail:
    msg: "lvm_volumes: must be a list"
  when:
    - lvm
    - not osd_auto_discovery
    - lvm_volumes is string

- name: make sure the devices variable is a list
  fail:
    msg: "devices: must be a list, not a string, i.e. [ \"/dev/sda\" ]"
  when:
    - collocated or non_collocated
    - devices is string

- name: make sure the dedicated_devices variable is a list
  fail:
    msg: "dedicated_devices: must be a list, not a string, i.e. [ \"/dev/sdj\" ]"
  when:
    - non_collocated
    - dedicated_devices is string

- name: verify journal devices have been populated in non-auto discovery
  fail:
    msg: "specify discovery option or pre-populate ceph journal devices in non-collocated osd scenario"
  when:
    - non_collocated
    - not osd_auto_discovery
    - dedicated_devices|length == 0

- name: verify non-collocation scenario and the devices and dedicated_devices lists
  fail:
    msg: "non-collocation scenario has mismatch in osd_auto_discovery, devices, and dedicated_devices lists"
  when:
    - non_collocated
    - (osd_auto_discovery and (devices|length > 0 or dedicated_devices|length > 0)) or (not osd_auto_discovery and (devices|length == 0 or dedicated_devices|length == 0))

- name: verify collocation scenario and the devices list
  fail:
    msg: "collocation scenario has mismatch in osd_auto_discovery and devices list"
  when:
    - collocated
    - (osd_auto_discovery and devices|length > 0) or (not osd_auto_discovery and devices|length == 0)

- name: check if bluestore is supported by the selected ceph version
  fail:
    msg: "bluestore is not supported by the selected Ceph version, use Luminous or above."
  when:
    - osd_objectstore == 'bluestore'
    - ceph_release_num[ceph_release] < ceph_release_num.luminous
