---
- name: scenario 3 - use lvm volumes to store OSD data and journal
  fail:
    msg: "OSD scenario {{ osd_scenario }} is not lvm"
  when: not lvm

- name: list all lvm osds
  command: ceph-volume lvm list
  register: ceph_volume_lvm_list
  failed_when: False
  changed_when: False
  check_mode: no

- name: use ceph-volume to create filestore osds with dedicated journals
  command: "ceph-volume --cluster {{ cluster }} lvm create --filestore --data {{ item.data_vg }}/{{ item.data }} --journal {{ item.journal }}"
  environment:
    CEPH_VOLUME_DEBUG: 1
  with_items: "{{ lvm_volumes }}"
  when:
    - item.journal_vg is not defined
    - osd_objectstore == 'filestore'
    - "'{{ item.data_vg }}/{{ item.data }}' not in ceph_volume_lvm_list.stdout"

- name: use ceph-volume to create filestore osds with dedicated lv journals
  command: "ceph-volume --cluster {{ cluster }} lvm create --filestore --data {{ item.data_vg }}/{{ item.data }} --journal {{item.journal_vg }}/{{ item.journal }}"
  environment:
    CEPH_VOLUME_DEBUG: 1
  with_items: "{{ lvm_volumes }}"
  when:
    - item.journal_vg is defined
    - osd_objectstore == 'filestore'
    - "'{{ item.data_vg }}/{{ item.data }}' not in ceph_volume_lvm_list.stdout"

- name: use ceph-volume to create bluestore osds with db and wal
  command: "ceph-volume --cluster {{ cluster }} lvm create --bluestore --data {{ item.data_vg }}/{{ item.data }} --block.wal {{ item.wal_vg }}/{{ item.wal }} --block.db {{ item.db_vg }}/{{ item.db }}"
  environment:
    CEPH_VOLUME_DEBUG: 1
  with_items: "{{ lvm_volumes }}"
  when:
    - osd_objectstore == 'bluestore'
    - item.wal is defined
    - item.wal_vg is defined
    - item.db is defined
    - item.db_vg is defined
    - "'{{ item.data_vg }}/{{ item.data }}' not in ceph_volume_lvm_list.stdout"

- name: use ceph-volume to create bluestore osds with db only
  command: "ceph-volume --cluster {{ cluster }} lvm create --bluestore --data {{ item.data_vg }}/{{ item.data }} --block.db {{ item.db_vg }}/{{ item.db }}"
  environment:
    CEPH_VOLUME_DEBUG: 1
  with_items: "{{ lvm_volumes }}"
  when:
    - osd_objectstore == 'bluestore'
    - item.wal is not defined
    - item.wal_vg is not defined
    - item.db is defined
    - item.db_vg is defined
    - "'{{ item.data_vg }}/{{ item.data }}' not in ceph_volume_lvm_list.stdout"

- name: use ceph-volume to create bluestore osds with wal only
  command: "ceph-volume --cluster {{ cluster }} lvm create --bluestore --data {{ item.data_vg }}/{{ item.data }} --block.wal {{ item.wal_vg }}/{{ item.wal }}"
  environment:
    CEPH_VOLUME_DEBUG: 1
  with_items: "{{ lvm_volumes }}"
  when:
    - osd_objectstore == 'bluestore'
    - item.wal is defined
    - item.wal_vg is defined
    - item.db is not defined
    - item.db_vg is not defined
    - "'{{ item.data_vg }}/{{ item.data }}' not in ceph_volume_lvm_list.stdout"

- name: use ceph-volume to create bluestore osds with just a data device
  command: "ceph-volume --cluster {{ cluster }} lvm create --bluestore --data {{ item.data_vg }}/{{ item.data }}"
  environment:
    CEPH_VOLUME_DEBUG: 1
  with_items: "{{ lvm_volumes }}"
  when:
    - osd_objectstore == 'bluestore'
    - item.wal is not defined
    - item.wal_vg is not defined
    - item.db is not defined
    - item.db_vg is not defined
    - "'{{ item.data_vg }}/{{ item.data }}' not in ceph_volume_lvm_list.stdout"
