---
- name: include check_mandatory_vars.yml
  include: check_mandatory_vars.yml

- name: include pre_requisite_containerized.yml
  include: pre_requisite_containerized.yml
  when: containerized_deployment

- name: include pre_requisite_non_containerized.yml
  include: pre_requisite_non_containerized.yml
  when: not containerized_deployment

- name: include create_mds_filesystems.yml
  include: create_mds_filesystems.yml
  when:
    - groups.get(mds_group_name, []) | length > 0
    - inventory_hostname == groups.get(mon_group_name) | last

- name: include calamari.yml
  include: calamari.yml
  when: calamari
