---

- assert:
    that: rbd_pool_exist.rc != 0
    msg: "Expect the rbd pool not exist in rbd_pool_luminous"

- name: create rbd pool on luminous
  shell: ceph --connect-timeout 5 --cluster {{ cluster }} osd pool create rbd {{ ceph_conf_overrides.global.osd_pool_default_pg_num }}
  changed_when: false
  failed_when: false
  run_once: true
